Repository pidp1/helpr-back-jfs5, pull requests merged in 2022-12, with the labels that each got.

#17 Limpeza do código
  src/main/java/org/soulcodeacademy/helpr/config/DevConfig.java
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/controllers/CargoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/CustomErrorResponse.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
  src/main/java/org/soulcodeacademy/helpr/repositories/CargoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ChamadoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/security/TokenFilter.java
  src/main/java/org/soulcodeacademy/helpr/security/TokenUtil.java
  src/main/java/org/soulcodeacademy/helpr/security/UsuarioSecurity.java
  src/main/java/org/soulcodeacademy/helpr/security/UsuarioSecurityService.java
  src/main/java/org/soulcodeacademy/helpr/services/AuthService.java
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/ParametrosInsuficientesError.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/RecursoNaoEncontradoError.java
  src/main/resources/application-dev.properties
Labels: enhancement

#21 [|BACK-END| Criar entidade de FuturoCandidato e Repository#2]
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
Labels: enhancement

#23 |BACK-END| Criar DTO de FuturoCandidato#7
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
Labels: enhancement

#26 Tratamento do erro DataIntegrityViolationException
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
Labels: enhancement

#27 Refatoração dos métodos de leitura das entidades
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#28 |BACK-END| Criar entidade de FuturoCandidato e Repository#2
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
Labels: enhancement

#30 Correcão populate
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: bug

#29 |BACK-END| Criar serviço de FuturoCandidato#4
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
Labels: enhancement

#31 dependenteDTO & dependente-Service
  src/main/java/org/soulcodeacademy/helpr/controllers/DependenteController.java
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/DependenteDTO.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/DependenteService.java
Labels: enhancement

#35 |BACK-END| Criar controller de FuturoCandidato#8
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#37 endpoint de chamado protegido com @PreAuthorize
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
Labels: enhancement

#38 endpoints de clientes protegidos
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
Labels: enhancement

#40 Configurar banco de dados de teste H2
  pom.xml
  src/main/java/org/soulcodeacademy/helpr/config/TestConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-test.properties
Labels: enhancement

#48 Criando usuário controller e service
  src/main/java/org/soulcodeacademy/helpr/controllers/UsuarioController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#49 procedures mysql
  mysql/Trabalhando com Procedure.sql
  mysql/proc_ajuste_salario.sql
  mysql/proc_lista_chamado_aberto_hoje.sql
Labels: enhancement

#51 Paginagem de usáuarios
  src/main/java/org/soulcodeacademy/helpr/controllers/UsuarioController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
Labels: enhancement

#52 Criação de procedures e correção do bug na senha
  mysql/Trabalhando com Procedure.sql
  mysql/proc_alteracao_imagem.sql
  mysql/proc_lista_chamado_fechados_hoje.sql
  mysql/readme.txt
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/resources/application-dev.properties
Labels: bug, enhancement

#53 Implementando o Swagger 2 na aplicação
  pom.xml
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/config/SpringFoxConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: documentation
